LOCAL_PATH:=$(call my-dir)

include $(CLEAR_VARS)
LOCAL_SRC_FILES:=hello.c
LOCAL_MODULE:=helloARM
LOCAL_CFLAGS+=-pie -fPIE
LOCAL_LDFLAGS+=-pie -fPIE
LOCAL_FORCE_STATIC_EXECUTABLE:=true

include $(BUILD_EXECUTABLE)

